### ISSUE TITLE
Replit support? 

### ISSUE THREAD

**Issue by LucasDiscordCzech** [biscxit/wumpus-gpt#1]
This git, doesn't work in replit, will there be support for replit hosting? Thanks!

**Comment by capibawa** [comment]
@LucasDiscordCzech I would love to look into it. Can you provide details about any errors you're receiving?

Edit: I noticed a problem with `libssl` stemming from Prisma. I wasn't able to figure it out so I opted to revert to Sequelize. No further issues have been observed from my end.

**Comment by LucasDiscordCzech** [comment]
Yup that'a the error, youre doing an amazing job by the way. Keep it up!
