### ISSUE TITLE
I can't use GPT-4 api

### ISSUE THREAD

**Issue by 0xydev** [biscxit/wumpus-gpt#4]
I changed the places I needed to change. But when I run the bot it gives the answers as gpt-3.

**Comment by LucasDiscordCzech** [comment]
Hi, gpt-4 uses a whole method of making ai responses, which means this code won't work.

**Comment by capibawa** [comment]
@0xydev The only thing you need to do is set the `OPENAI_MODEL` field to `gpt-4` in your .env file. Then, restart the bot if it's already running.

**Comment by 0xydev** [comment]
The bot is working, but when I ask the bot which version it's using, I get GPT-3 as the answer. When I ask the same question to Chat GPT Plus, I get GPT-4 as the answer. I'm not sure if there's a problem with the API or if it stems from the GPT-3 tokenizer in your code. How else can I test it?

**Comment by capibawa** [comment]
@0xydev GPT-4 isn’t aware of its own version, ChatGPT likely has a system prompt set to avoid that confusion. I can think of two ways you can confirm that the bot is using GPT-4:

1. Log the request payload before it’s sent to the API, ensuring that `model` is indeed `gpt-4`.
2. Ask the bot, “There are 50 books in a library. Sam decides to read 5 of the books. How many books are there now?” If it responds with 45, it is likely **not** GPT-4.
